# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6dd7dfbe3f8a8c8dc9d16208ea4b77dcd7de02c0f1dbc22621578fb47a151905de13aba06594da1e2c07509ce99080957ba216df2986738530663cc2a75a041

test:
  secret_key_base: ede3cff10715624c44daa3f737bf5797004160f49538dcaf0275385b01642ea2046780460fd7ba3ae7b6640a09bd64ee088459bdd9d28ec547ed1cefb8652114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
